### ISSUE TITLE
Reset Zoom zooms out past data

### ISSUE THREAD

**Issue by spencerwahl** [RAMP-PCAR/dqvue#17]
On certain charts (cip) it seems that the reset zoom is zooming out to a starting point of 0, and not the config specified starting point.

**Comment by AleksueiR** [comment]
`minPadding` was set to high on the chart causing a large gap between the lowest data point and the edge of the chart. See here for details: https://github.com/highcharts/highcharts/blob/9be60aa/js/parts/Axis.js#L1044
