### ISSUE TITLE
Problem with constraining minimum range

### ISSUE THREAD

**Issue by spencerwahl** [RAMP-PCAR/dqvue#18]
Found by Aly:

If you have a chart with a minimum range, shrink the range to the minimum, pull the bar to the right then select (on the right side of the chart) a smaller range to view. The slider will shrink to the smaller view but the chart is correctly constrained still.

**Comment by AleksueiR** [comment]
`minPadding` was set to high on the chart which caused this weird behaviour. Not a DQVue issue.
