### ISSUE TITLE
Implement a horizontal (xAxis) zoom slider

### ISSUE THREAD

**Issue by AleksueiR** [RAMP-PCAR/dqvue#4]
Higcharts [zoom feature](https://api.highcharts.com/highcharts/chart.zoomType) does not have an accessible alternative.

Add a slider to charts allowing the user to constrain the amount of data displayed along the X axis (Y and Z axis sliders to be added later).
Library to use: https://refreshless.com/nouislider/

- [x] display slider if chart's `zoomType` is set to `x` or `xy`
- [x] make slider keyboard accessible
- [x] provide additional text fields for direct entry
- [x] make sure default slider configuration doesn't break the chart
- [x] add an option to supply a full slider configuration along with the chart config

Note: some chart types (pie, heatmap, etc.) do not have X axis and should not display the slider.

**Comment by AleksueiR** [comment]
Providing additional fields for direct entry is a bit more complicated than expected as axes' type can be set to `linear`, `logarithmic`, `datetime` or `category`. 
https://api.highcharts.com/highcharts/xAxis.type

`Linear` and `logarithmic` can be served by simple text input fields restricted to numbers - this works just fine.

`Category` uses the names specified in config to mark the axis. It works with a text input field, but maps category names to their indexes:
![](https://i.imgur.com/b7KgMDP.png)
In this case a dropdown with category options would be more appropriate.

`Datetime` expects numbers in milliseconds and marks axis with appropriate dates:
![](https://i.imgur.com/gqTFpLT.png)

Using simple input fields doesn't make much sense as they are nary usable:
![](https://i.imgur.com/Shic95x.png)

Instead, a date/time picker needs to be provided. But which one? Do we want just a day picker, or a time picker, or should this be configurable by the config author? WET uses the standard [HTML5 datepicker](http://wet-boew.github.io/v4.0-ci/demos/datepicker/datepicker-en.html), so it's probably the safest choice for now.

**Comment by mweech** [comment]
+1 for using the WET HTML5 datepicker
