### ISSUE TITLE
First graph increases in height when zoom in or out through a browser

### ISSUE THREAD

**Issue by barryytm** [RAMP-PCAR/dqvue#40]
This is an issue I stumbled upon while I was looking at one of the the CESI detail pages.  When zooming in or out through a browser, the height of the first graph will increase, and it will not go back to its original height. 

Link: http://indicators-map.canada.ca/App/Detail?id=0260104&GoCTemplateCulture=en-CA

**Comment by AleksueiR** [comment]
Doesn't seem to be a DQV bug.

The container for the text just above the first chart should have a `row` class, not ` col-md-12`. The column class makes it float which takes it out of the regular layout and apparently confuses the Highcharts renderer is extending the chart itself.

![](https://i.imgur.com/t05BHgv.png)
